# Generated by Django 5.0.1 on 2024-01-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_app', '0002_portfolio_user_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='btc_total',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='eth_total',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='ltc_total',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
