# Generated by Django 5.0.1 on 2024-01-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_app', '0003_alter_portfolio_btc_total_alter_portfolio_eth_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='currency',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
